# Generated by Django 2.2.19 on 2021-08-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210822_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.TextField(null=True, verbose_name='Автор'),
        ),
    ]
