# Generated by Django 2.2.19 on 2021-08-16 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodgramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=150, verbose_name='Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Surname')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registration date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ('username',),
            },
        ),
    ]
