# Generated by Django 2.2.19 on 2021-08-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210818_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodgramuser',
            old_name='admin',
            new_name='is_staff',
        ),
        migrations.RemoveField(
            model_name='foodgramuser',
            name='staff',
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
