# Generated by Django 2.2.19 on 2021-08-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210818_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodgramuser',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
