# Generated by Django 2.2.19 on 2021-09-06 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_foodgramuser_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodgramuser',
            name='date_joined',
        ),
    ]
